services:
  database:
    image: postgres:latest
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=${DATABASE}
      - POSTGRES_USER=${USER}
      - POSTGRES_PASSWORD=${PASSWORD}
    networks:
      - theauth-networks

      
  backend-api:
    image: rfauzi/theauth-api:latest
    depends_on:
      - database
    restart: unless-stopped
    ports:
      - "3001:443"
    env_file:
      - .env
    networks:
      - theauth-networks

networks:
  theauth-networks:
    driver: bridge